### ISSUE TITLE
[Improvement] Add the mod to the Steam Workshop

### ISSUE THREAD

**Issue by AvaPL** [psykana/dos2deck#1]
Hi,

I tried it and works well. Thank you for an awesome contribution to the DOS2 Steam Deck community!

Would it be possible to add it to the Steam Workshop? I would facilitate the installation for a lot of users.

**Comment by psykana** [comment]
DLL's are out of scope of Divinity Engine tool and Workshop, so I don't think there's a way to publish it. Norbyte's script extender is not in Workshop either.
