### ISSUE TITLE
Game doesn’t start 

### ISSUE THREAD

**Issue by Zolotarskyi** [psykana/dos2deck#3]
Hi! I have Steam deck and did everything following the instructions, but game didn’t start. Just valve logo and then back to game page in library.
Please, could you check is it still working with last version Dos2 De?

**Comment by Ssiao33** [comment]
Just commenting cuz I got the same issue

**Comment by psykana** [comment]
Hi, I just tried to reproduce this issue but it's fine on my end.
Please update your deck to latest Stable (although I'm on 3.5.3 Beta), verify integrity of game files in Steam and revert to default compatibility tools if you changed that.
If the issue persists, delete `d3d11.dll` and troubleshoot from there - AFAIK, this patch doesn't really do anything that can prevent the game from booting...

**Comment by rickstevenss** [comment]
Hi, I'm also having this issue. Latest stable, game updated, the game won't start only if this dll is present

**Comment by psykana** [comment]
Hi @rickstevenss,
Today I factory reset my deck to latest stable, tested the release dll and everything worked fine.
Could you please check the game directory for any crash dumps?

**Comment by Mishadawai** [comment]
Unfortunately I have the same issue. I run the **gog** version with latest stable Firmware. Could it be that this is only working with the **steam** version ? 
when I delete the file it will start again as usual.

**Comment by psykana** [comment]
@Mishadawai, I don't know how gog works but please try to run the game with `WINEDLLOVERRIDES="d3d11.dll=n,b" %command%` in the launch options.

**Comment by rickstevenss** [comment]
Hi @psykana and thank you for looking into this. I also have the GoG version, could this be why? Though there are crash dumps there indeed (even though I don't know how to read them). Should I attach the latest crash dump here? With the above launch options it also doesn't launch.

Edit: attaching dump
[CrashDump - 05-29-2024 02h 45m 28s.zip](https://github.com/psykana/dos2deck/files/15488935/CrashDump.-.05-29-2024.02h.45m.28s.zip)

**Comment by psykana** [comment]
@rickstevenss @Mishadawai please try the new release

**Comment by rickstevenss** [comment]
@psykana thanks a lot for the newest update and your hard work! It works with the GOG version now (for people still crashing, use Proton 7)
